### ISSUE TITLE
TODO list for version 0.2

### ISSUE THREAD

**Issue by radhakrishnatg** [NEMRI-org/primo-optimizer#26]
This issue tracks the TODO list for cutting 0.2 release.

- [x] Merge a basic version of `result_parser.py`  file (Must display KPIs and efficiency scores at least.). Lead: @strahlw  @DevKakkad32 Please coordinate with Will and split the work with him if needed.
        - Completed in PR #28 (NOTE: We need to update the efficiency calculations to be consistent with the efficiency model.)
- [x] Update all case study notebooks and make sure there are no issues with the code. Lead: @DevKakkad32 for Case Study 1 and @ruonanli61 for Case Study 2.
        - Case Study 1 is completed. Waiting to update the case study 2. 
- [x] Federal DAC data is supported. Lead: @apd-ypuranik 
        - Addressed in PR #37 
- [x] Ensure test coverage is 100% for all the new code. Lead: @radhakrishnatg 
- [x] Basic version of backfill and re-optimize. Lead: @ruonanli61 
    - Completed in PR #45 
- [x] Remove old scripts which are no longer needed. #49 
- [ ] Some of the log messages are very long, so the user may need to use the slider to read the entire message. Go through the entire repo and break long log messages into multiple lines. Lead: TBD
- [ ] Enforce data type (`dtype`) while reading the data from an excel or csv file for supported columns/metrics. One approach: Add a method in the `WellDataColumnNames` class that returns the data types for all columns that are needed to be read. Lead: TBD

The last two are a low priority. But everything else is a high priority.

**Comment by apd-ypuranik** [comment]
@radhakrishnatg : Just a note. The Case Study notebooks are complete. Test coverage is also in a good spot.

**Comment by apd-ypuranik** [comment]
Since v0.2.0 has already been released, closing this issue, even though the lower priority items may still be incomplete.
